<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Секрет, который Telegram присылает в заголовке X-Telegram-Bot-Api-Secret-Token.
    // Должен совпадать с secret_token, переданным в setWebhook; команда nutgram:hook:set
    // в safe_mode использует md5(APP_KEY) — это и есть значение по умолчанию.
    'webhook_secret' => env('TELEGRAM_WEBHOOK_SECRET') ?: md5((string) env('APP_KEY')),

    // Extra or specific configurations
    'config' => [],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
